name: Release APK

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Extract key
        run: echo "${{ secrets.RELEASE_KEY }}" | base64 --decode > release-key.jks

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Extract version name
        id: extract_version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"')
          echo "VERSION_NAME=$VERSION_NAME"
          echo "::set-output name=version_name::$VERSION_NAME"

      - name: Extract changelog
        id: extract_changelog
        run: |
          CHANGELOG=$(cat CHANGELOG)
          echo "CHANGELOG=$CHANGELOG"
          echo "::set-output name=CHANGELOG::$CHANGELOG"

      - name: Build and Sign APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: release-key.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            LICENSE
          name: ${{ steps.extract_version.outputs.version_name }}
          tag_name: ${{ steps.extract_version.outputs.version_name }}
          body: ${{ steps.extract_changelog.outputs.CHANGELOG }}